<h1>Pytorch</h1>

- Define by Run (cf. Tensorflow : Define and Run)

<h1>Pytorch Packages</h1>

 - [**torch**](https://pytorch.org/docs/stable/torch.html)
 - [torch.autograd](https://pytorch.org/docs/stable/autograd.html)
 - [torch.nn](https://pytorch.org/docs/stable/nn.html)
 - [torch.optim](https://pytorch.org/docs/stable/optim.html)
 - [torch.multiprocessing](https://pytorch.org/docs/stable/multiprocessing.html)
 - torch.utils
 - torch.legact

# Pytorch Tensor Basic Usage

1. Create Tensor
2. Math Operations
3. Tensor to Numpy, Numpy to Tensor
4. Tensor on GPU
5. Indexing, Joining, Slicing
6. Initialization

<br> 
## 1. Create Tensor

### 1) Random numbers

In [1]:
import torch

In [2]:
# torch.rand(size)
# make tensor from X ~ U(0, 1)
x = torch.rand(2, 3)
x

tensor([[0.2926, 0.5586, 0.4849],
        [0.2292, 0.3932, 0.6602]])

In [3]:
# torch.randn(size)
# make tensor from X ~ Z(0, 1)
x = torch.randn(2,3)
x

tensor([[-0.6716, -0.9535, -0.8025],
        [-1.5024,  1.1510,  0.3891]])

In [4]:
# torch.randperm(n)
# permutation n elements
x = torch.randperm(5)
x

tensor([1, 4, 2, 3, 0])

### 2) Empty, Zeros, Ones, Arange, Max

In [5]:
# torch.empty(size)
# make tensor with trash uninitialized data
x = torch.empty(2,3)
x

tensor([[2.1822e-01, 3.0722e-41, 3.3631e-44],
        [0.0000e+00,        nan, 3.8910e-01]])

In [6]:
# torch.zeros(size)
# make tensor with 0
x = torch.zeros(2, 3)
x

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
# torch.ones(size)
# make tensor with 1
x = torch.ones(2, 3)
x

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [8]:
# torch.arange(start=0, end, step= 1)
# make arithmetic sequence tensor
x = torch.arange(0, 3, step=0.3)
x

tensor([0.0000, 0.3000, 0.6000, 0.9000, 1.2000, 1.5000, 1.8000, 2.1000, 2.4000,
        2.7000])

In [9]:
# check size of tensor
x.size()

torch.Size([10])

In [10]:
# torch.max(input, dim, keepdim=False, out=None) -> (Tensor, LongTensor)
# find max of tensor
x = torch.rand(2, 3)
print(x)
print()
print('max is', torch.max(x))
print()
print('position of max value in 0 dim is\n', torch.max(x, 0))
print()
print('position of max value in 1 dim is\n', torch.max(x, 1))

tensor([[0.4356, 0.4372, 0.7418],
        [0.2238, 0.4011, 0.6099]])

max is tensor(0.7418)

position of max value in 0 dim is
 torch.return_types.max(
values=tensor([0.4356, 0.4372, 0.7418]),
indices=tensor([0, 0, 0]))

position of max value in 1 dim is
 torch.return_types.max(
values=tensor([0.7418, 0.6099]),
indices=tensor([2, 2]))


### 3) Tensor Data Type

| Data type               | dtype                                         | Tensor types                 |
|:-------------------------|:-----------------------------------------------|:------------------------------|
| 32-bit floating point   | ``` torch.float32 ``` or ``` torch.float ```  | ``` torch.*.FloatTensor ```  |
| 64-bit floating point   | ``` torch.float64 ``` or ``` torch.double ``` | ``` torch.*.DoubleTensor ``` |
| 16-bit floating point   | ``` torch.float16 ``` or ``` torch.half ```   | ``` torch.*.HalfTensor ```   |
| 16-bit integer (signed) | ``` torch.int16 ``` or ``` torch.short ```    | ``` torch.*.ShortTensor ```  |
| 32-bit integer (signed) | ``` torch.int32 ``` or ``` torch.int ```      | ``` torch.*.IntTensor ```    |
| 64-bit integer (signed) | ``` torch.int64 ``` or ``` torch.long ```     | ``` torch.*.LongTensor ```   |

In [11]:
# torch.tensor(size or list, dtype=torch.floattensor)
x = torch.tensor([5.4, 3])
x

tensor([5.4000, 3.0000])

In [12]:
# torch.FloatTensor(size or list)
x = torch.FloatTensor(2, 3)
print(x)
print()
x = torch.FloatTensor([2, 3])
print(x)

tensor([[2.1823e-01, 3.0722e-41, 3.7835e-44],
        [0.0000e+00,        nan, 0.0000e+00]])

tensor([2., 3.])


In [13]:
x = torch.empty(2, 3, dtype=torch.float)
y = torch.zeros(2, 3, dtype = torch.long)
z = torch.arange(0, 3, step=0.5, dtype=torch.double)

print(x)
print(y)
print(z)

tensor([[2.1823e-01, 3.0722e-41, 3.7835e-44],
        [0.0000e+00,        nan, 0.0000e+00]])
tensor([[0, 0, 0],
        [0, 0, 0]])
tensor([0.0000, 0.5000, 1.0000, 1.5000, 2.0000, 2.5000], dtype=torch.float64)


In [14]:
# tensor.type_as(tensor_type)
x = torch.FloatTensor([2, 3])
print(x)
print(x)
x = x.type_as(torch.IntTensor())
print(x)

tensor([2., 3.])
tensor([2., 3.])
tensor([2, 3], dtype=torch.int32)


### 4) Tensor Size

In [15]:
#5,3 차원의 새로운 텐서를 생성합니다.
x = x.new_ones(5,3, dtype=torch.double)
print(x)
print()
# x와 같은 size에서 랜덤한 숫자로 채워진 텐서를 생성합니다
y = torch.randn_like(x,dtype=torch.float)
print(y)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

tensor([[-1.3207,  0.2037, -0.4571],
        [-0.8858, -1.0157, -0.0705],
        [ 1.5296,  1.1297,  0.2432],
        [ 0.3710,  1.0527,  2.0284],
        [ 1.9539,  0.5699,  0.6649]])


## 2. Math Operations

### 1) add, mul, div

In [16]:
# torch.add(input, other)

x1 = torch.FloatTensor([[1, 2, 3], [4, 5, 6]])
x2 = torch.FloatTensor([[0, 3, 6], [10, 20, 30]])

add = torch.add(x1, x2)

print(add)
print(x1 + x2)

tensor([[ 1.,  5.,  9.],
        [14., 25., 36.]])
tensor([[ 1.,  5.,  9.],
        [14., 25., 36.]])


In [17]:
# 차원이 다르더라도 안쪽 차원만 같으면 연산이 가능합니다.
x = torch.rand(1, 5, 3)
y = torch.rand(5, 3)
print(x)
print()
print(y)
print()
print(torch.add(x, y))

tensor([[[0.6853, 0.8599, 0.7059],
         [0.9432, 0.9434, 0.9197],
         [0.6869, 0.7558, 0.6794],
         [0.1522, 0.1239, 0.6906],
         [0.2626, 0.6868, 0.2044]]])

tensor([[0.6721, 0.7710, 0.1007],
        [0.9399, 0.1696, 0.4442],
        [0.7750, 0.4620, 0.9187],
        [0.8260, 0.1979, 0.7134],
        [0.6356, 0.8564, 0.8192]])

tensor([[[1.3573, 1.6309, 0.8066],
         [1.8830, 1.1129, 1.3639],
         [1.4619, 1.2178, 1.5982],
         [0.9782, 0.3217, 1.4040],
         [0.8982, 1.5432, 1.0235]]])


In [18]:
# torch.add 말고 add_의 경우에는 이러한 연산 기능이 지원되지 않습니다. 따라서 먼저 x를 같은 차원으로 바꿔줍니다.
print(y.add_(x))

RuntimeError: ignored

In [19]:
x = torch.rand(5,3)
y.add_(x)
print(y)

tensor([[1.1117, 1.7169, 0.3773],
        [0.9585, 1.0737, 0.6946],
        [1.2316, 0.6550, 1.4193],
        [1.6979, 0.6967, 1.1381],
        [1.0826, 1.4433, 1.1854]])


In [20]:
# x 텐서의 2열을 불러옵니다. numpy 연산이 지원됩니다.

print(x)
print(x.shape)
print(x[:,1])
print(x[:,1].shape)

tensor([[0.4396, 0.9459, 0.2766],
        [0.0187, 0.9041, 0.2504],
        [0.4566, 0.1930, 0.5006],
        [0.8719, 0.4989, 0.4246],
        [0.4470, 0.5870, 0.3662]])
torch.Size([5, 3])
tensor([0.9459, 0.9041, 0.1930, 0.4989, 0.5870])
torch.Size([5])


In [21]:
# torch.mul(input, other)
x1 = torch.FloatTensor([[1, 2, 3], [4, 5, 6]])
x2 = torch.FloatTensor([[1, 2, 3], [4, 5, 6]])

print(torch.mul(x1, x2))

tensor([[ 1.,  4.,  9.],
        [16., 25., 36.]])


In [22]:
print(torch.mul(x1, 10))

tensor([[10., 20., 30.],
        [40., 50., 60.]])


In [23]:
# torch.div(input, other)
print(torch.div(x1, x2))

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [24]:
print(torch.div(x1, 5))

tensor([[0.2000, 0.4000, 0.6000],
        [0.8000, 1.0000, 1.2000]])


### 2) pow, exp, log

In [25]:
# torch.pow(input, exponent)
x = torch.rand(3, 4)

print(x)
print()
print(torch.pow(x, 3))

tensor([[0.3952, 0.8534, 0.7093, 0.7955],
        [0.7825, 0.3196, 0.0910, 0.4737],
        [0.4315, 0.0304, 0.7692, 0.7370]])

tensor([[6.1737e-02, 6.2160e-01, 3.5682e-01, 5.0338e-01],
        [4.7911e-01, 3.2638e-02, 7.5436e-04, 1.0628e-01],
        [8.0362e-02, 2.7970e-05, 4.5517e-01, 4.0038e-01]])


In [26]:
# torch.exp(input, out=None)
x = torch.rand(3, 4)

print(x)
print()
print(torch.exp(x))

tensor([[0.7862, 0.0964, 0.0584, 0.5243],
        [0.1039, 0.0034, 0.9350, 0.4851],
        [0.2066, 0.9026, 0.4371, 0.6185]])

tensor([[2.1951, 1.1012, 1.0602, 1.6893],
        [1.1095, 1.0034, 2.5471, 1.6243],
        [1.2295, 2.4661, 1.5482, 1.8562]])


In [27]:
# torch.log(input, out)
# ln
x = torch.rand(3, 4)

print(x)
print()
print(torch.log(x))

tensor([[0.4831, 0.4223, 0.2509, 0.6203],
        [0.5448, 0.1375, 0.8465, 0.0101],
        [0.3418, 0.3863, 0.1622, 0.7418]])

tensor([[-0.7276, -0.8620, -1.3825, -0.4775],
        [-0.6073, -1.9843, -0.1667, -4.5910],
        [-1.0736, -0.9510, -1.8188, -0.2987]])


In [28]:
# torch.mm(input, mat2)
# matrix multiplication
x1 = torch.rand(3, 4)
x2 = torch.rand(4, 5)

print(x1)
print(x2)
print()
print(torch.mm(x1, x2))

tensor([[0.7067, 0.3864, 0.5334, 0.3829],
        [0.8394, 0.8952, 0.5240, 0.2926],
        [0.0032, 0.4960, 0.9991, 0.0528]])
tensor([[0.3597, 0.6862, 0.7440, 0.7204, 0.6992],
        [0.7917, 0.3698, 0.5707, 0.2274, 0.8478],
        [0.5404, 0.6442, 0.9370, 0.9779, 0.4107],
        [0.3775, 0.2816, 0.0464, 0.6320, 0.2114]])

tensor([[0.9929, 1.0793, 1.2639, 1.3605, 1.1217],
        [1.4042, 1.3270, 1.6400, 1.5056, 1.6229],
        [0.9537, 0.8441, 1.2241, 1.1255, 0.8443]])


In [29]:
# torch.bmm(input, mat2)
# batch matrix - matirx product

x1 = torch.rand(10, 3, 4)
x2 = torch.rand(10, 4, 5)

torch.bmm(x1, x2).size()

torch.Size([10, 3, 5])

In [30]:
# torch.dot(input, other)
# dot product
torch.dot(torch.tensor([2, 3]), torch.tensor([3, 4]))

tensor(18)

In [31]:
# torch.t(input)
# transpose
x = torch.rand(3, 4)
print(x.size(), x.t().size())

torch.Size([3, 4]) torch.Size([4, 3])


In [32]:
# torch.transpose(input, dim0, dim1)
x = torch.rand(3, 2, 4)
print(x)
print()
print(torch.transpose(x, 1, 2))
print()
print(x.transpose(1,2))

tensor([[[0.3357, 0.6025, 0.9860, 0.9729],
         [0.7820, 0.1930, 0.2071, 0.1485]],

        [[0.9765, 0.2750, 0.7225, 0.5592],
         [0.4651, 0.0800, 0.9279, 0.6707]],

        [[0.1343, 0.6826, 0.7093, 0.2829],
         [0.9960, 0.6354, 0.5812, 0.4405]]])

tensor([[[0.3357, 0.7820],
         [0.6025, 0.1930],
         [0.9860, 0.2071],
         [0.9729, 0.1485]],

        [[0.9765, 0.4651],
         [0.2750, 0.0800],
         [0.7225, 0.9279],
         [0.5592, 0.6707]],

        [[0.1343, 0.9960],
         [0.6826, 0.6354],
         [0.7093, 0.5812],
         [0.2829, 0.4405]]])

tensor([[[0.3357, 0.7820],
         [0.6025, 0.1930],
         [0.9860, 0.2071],
         [0.9729, 0.1485]],

        [[0.9765, 0.4651],
         [0.2750, 0.0800],
         [0.7225, 0.9279],
         [0.5592, 0.6707]],

        [[0.1343, 0.9960],
         [0.6826, 0.6354],
         [0.7093, 0.5812],
         [0.2829, 0.4405]]])


In [33]:
# torch.eig(a, eigenvectors=False)
# eigen value, eigen vector
x = torch.rand(2, 2)
print(x)
print()
print(torch.eig(x, True))

tensor([[0.5583, 0.8665],
        [0.4806, 0.9913]])

torch.return_types.eig(
eigenvalues=tensor([[0.0941, 0.0000],
        [1.4555, 0.0000]]),
eigenvectors=tensor([[-0.8815, -0.6947],
        [ 0.4722, -0.7193]]))


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: UserWarning: torch.eig is deprecated in favor of torch.linalg.eig and will be removed in a future PyTorch release.
torch.linalg.eig returns complex tensors of dtype cfloat or cdouble rather than real tensors mimicking complex tensors.
L, _ = torch.eig(A)
should be replaced with
L_complex = torch.linalg.eigvals(A)
and
L, V = torch.eig(A, eigenvectors=True)
should be replaced with
L_complex, V_complex = torch.linalg.eig(A) (Triggered internally at  ../aten/src/ATen/native/BatchLinearAlgebra.cpp:2894.)
  


## 3. Tensor to Numpy, Numpy to Tensor

In [34]:
import numpy as np

In [35]:
a = torch.ones(5)

In [36]:
# tensor.numpy()
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [37]:
# torch.from_numpy(ndarray)
a = np.ones(5)
b = torch.from_numpy(a)

print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [38]:
np.add(a, 1, out=a)

print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


## 4. Tensor to Numpy, Numpy to Tensor

In [39]:
x= torch.FloatTensor([[1,2,3],[4,5,6]])

if torch.cuda.is_available():
    x_cuda = x.cuda()
    print("sap able")
else:
    x_cuda = x.cpu()
    print("bul able")
    
print(x_cuda)

sap able
tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0')


In [40]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    
    y = torch.ones_like(x,device=device)
    x = x.to(device)
    z = x+y
    print(z)
    print(z.to("cpu")) #.to 기능을 tensor를 GPU로 연산할 수 있습니다
    print(z.to("cuda"))

tensor([[2., 3., 4.],
        [5., 6., 7.]], device='cuda:0')
tensor([[2., 3., 4.],
        [5., 6., 7.]])
tensor([[2., 3., 4.],
        [5., 6., 7.]], device='cuda:0')


## 5. Indexing, Slicing, Joining

### 1) Indexing

In [41]:
# tensor.index_select(input, dim, index)
# index must be Longtensor
x = torch.rand(4, 3)
y = torch.index_select(x, 0, torch.LongTensor([0, 3]))

print(x)
print()
print(y)

tensor([[0.1657, 0.1739, 0.8958],
        [0.8609, 0.5698, 0.4341],
        [0.6706, 0.3232, 0.4731],
        [0.9792, 0.0852, 0.1092]])

tensor([[0.1657, 0.1739, 0.8958],
        [0.9792, 0.0852, 0.1092]])


In [42]:
print(x[:, 0])
print()
print(x[0, :])
print()
print(x[0:2, 0:2])

tensor([0.1657, 0.8609, 0.6706, 0.9792])

tensor([0.1657, 0.1739, 0.8958])

tensor([[0.1657, 0.1739],
        [0.8609, 0.5698]])


### 2) Joining

In [43]:
# torch.cat(tensors, dim)
x = torch.FloatTensor([[1, 2, 3],
                       [4, 5, 6]])
y = torch.FloatTensor([[7, 8, 9],
                       [10, 11, 12]])

print(torch.cat([x, y], dim=0))
print(torch.cat([x, y], dim=1))

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])
tensor([[ 1.,  2.,  3.,  7.,  8.,  9.],
        [ 4.,  5.,  6., 10., 11., 12.]])


In [44]:
# torch.stack(tensors, dim=0)
print(torch.stack([x, y], dim=0))
print()
print(torch.stack([x, y], dim=1))
print()
print(torch.stack([x, y], dim=2))

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.]],

        [[ 7.,  8.,  9.],
         [10., 11., 12.]]])

tensor([[[ 1.,  2.,  3.],
         [ 7.,  8.,  9.]],

        [[ 4.,  5.,  6.],
         [10., 11., 12.]]])

tensor([[[ 1.,  7.],
         [ 2.,  8.],
         [ 3.,  9.]],

        [[ 4., 10.],
         [ 5., 11.],
         [ 6., 12.]]])


### 3) Slicing

In [45]:
# torch.chunk(tensor, chunks, dim=0)
# tensor를 chunk 단위로 쪼갭니다. chunk 개수 만큼 생성합니다.

x = torch.FloatTensor([[1,2,3],
                       [4,5,6]])
y = torch.FloatTensor([[7,8,9],
                       [10,11,12]])
z1 = torch.cat([x,y],dim = 0)

x_1, x_2 = torch.chunk(z1,2,dim=0)
y_1, y_2, y_3 = torch.chunk(z1,3,dim=1)

print(z1)
print(x_1)
print(x_2)
print(y_1)
print(y_2)
print(y_3)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])
tensor([[ 1.],
        [ 4.],
        [ 7.],
        [10.]])
tensor([[ 2.],
        [ 5.],
        [ 8.],
        [11.]])
tensor([[ 3.],
        [ 6.],
        [ 9.],
        [12.]])


In [46]:
# torch.split(tensor,split_size,dim=0) 각 size가 split_size만큼인 것을 생성합니다.
x = torch.FloatTensor([[1,2,3],
                       [4,5,6]])
y = torch.FloatTensor([[7,8,9],
                       [10,11,12]])
z1 = torch.cat([x,y],dim = 0)

x1,x2 = torch.split(z1,2,dim=0)
y1,y2 = torch.split(z1,2,dim=1)

print(z1)
print(x1)
print(x2)
print(y1)
print(y2)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])
tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])
tensor([[ 3.],
        [ 6.],
        [ 9.],
        [12.]])


### 4) squeezing

In [47]:
# torch.squeeze(input, dim=None)
# 1짜리 차원을 줄입니다.
x1 = torch.FloatTensor(10,1,3,1,4)
x2 = torch.squeeze(x1)

x1.size(), x2.size()

(torch.Size([10, 1, 3, 1, 4]), torch.Size([10, 3, 4]))

In [48]:
# torch.unsqueeze(input,dim=None)
# 1짜리 차원을 더합니다.
x1 = torch.FloatTensor(10,3,4)
x2 = torch.unsqueeze(x1,dim=0)

x.size(), x2.size()

(torch.Size([2, 3]), torch.Size([1, 10, 3, 4]))

## 6. Initialization

In [49]:
import torch.nn.init as init


x1 = init.uniform_(torch.FloatTensor(3,4),a=0,b=9) 
x2 = init.normal_(torch.FloatTensor(3,4),std=0.2)
x3 = init.constant_(torch.FloatTensor(3,4),3.1415)

x1, x2, x3

(tensor([[7.4343, 2.5757, 2.9748, 6.1057],
         [7.0012, 8.4568, 3.8159, 1.2852],
         [2.5544, 8.8383, 0.8613, 1.8796]]),
 tensor([[ 0.0875, -0.1597,  0.0812,  0.1461],
         [-0.0445, -0.2527,  0.0195, -0.1608],
         [-0.0926,  0.1048,  0.2773,  0.0004]]),
 tensor([[3.1415, 3.1415, 3.1415, 3.1415],
         [3.1415, 3.1415, 3.1415, 3.1415],
         [3.1415, 3.1415, 3.1415, 3.1415]]))

# Autograd Package

- Autograd 패키지는 tensor의 모든 연산에 자동 미분을 제공합니다. 이는 define-by-run의 프레임워크로 코드를 어떻게 작성하느냐에 따라 역전파가 정의된다는 뜻입니다. 역전파는 학습과정의 매 단계마다 달라집니다.
- requires_grad 속성을 True로 설정하면 해당 tensor의 모든 연산을 추적합니다. 계산이 완료된 후 .backward()를 호출해 gradient를 자동으로 계산할 수 있습니다. 이 tensor의 gradient는 .grad에 누적됩니다.
- 연산 기록을 추적하는 것을 멈추기 위해 코드 블럭을 with torch.no_grad():로 감쌀 수 있습니다. gradient는 필요 없지만 requires_grad=True가 설정되어 학습 가능한 Parameter(매개변수)를 갖는 모델을 평가할 때 유용합니다.

## 예시 1

In [50]:
a = torch.randn(2,2)
a = ((a*3)/(a-1)) 
print(a.requires_grad)
print(a.grad_fn)

False
None


In [51]:
a.requires_grad_(True)
print(a.requires_grad)
print(a.grad_fn)

True
None


In [52]:
b = (a*a).sum()
print(b.grad_fn)

## 예시 2

In [53]:
x = torch.ones(2, 2, requires_grad=True)
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [54]:
z = y*y*3
out = z.mean()
print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


### Gradient

- 직접 계산

In [55]:
x_grad = 1.5 * (x+2)
x_grad

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]], grad_fn=<MulBackward0>)

- Autograd 이용

In [56]:
# out = 3 * (x + 2) ^ 2
print(out)
out.backward()

tensor(27., grad_fn=<MeanBackward0>)


In [57]:
print(x)
print(x.grad)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


## 예시 3

In [58]:
x = torch.randn(3, requires_grad=True)

y = x*2
i = 1

while y.data.norm() < 1000:
    i += 1
    y *= 2

    print(y, y.data.norm())
    print(i)

tensor([-0.7201,  0.0412,  4.4323], grad_fn=<MulBackward0>) tensor(4.4906)
2
tensor([-1.4401,  0.0824,  8.8647], grad_fn=<MulBackward0>) tensor(8.9812)
3
tensor([-2.8803,  0.1648, 17.7293], grad_fn=<MulBackward0>) tensor(17.9625)
4
tensor([-5.7606,  0.3295, 35.4586], grad_fn=<MulBackward0>) tensor(35.9250)
5
tensor([-11.5212,   0.6590,  70.9172], grad_fn=<MulBackward0>) tensor(71.8500)
6
tensor([-23.0424,   1.3180, 141.8344], grad_fn=<MulBackward0>) tensor(143.7000)
7
tensor([-46.0847,   2.6361, 283.6688], grad_fn=<MulBackward0>) tensor(287.4000)
8
tensor([-92.1694,   5.2722, 567.3376], grad_fn=<MulBackward0>) tensor(574.8000)
9
tensor([-184.3389,   10.5443, 1134.6753], grad_fn=<MulBackward0>) tensor(1149.6000)
10


In [59]:
print(y)
gradients = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(gradients)

print(x.grad)

tensor([-184.3389,   10.5443, 1134.6753], grad_fn=<MulBackward0>)
tensor([1.0240e+02, 1.0240e+03, 1.0240e-01])


## 예시 4

In [60]:
print(x.requires_grad)
print((x**2).requires_grad)

with torch.no_grad():
    print((x**2).requires_grad)

print((x**2).requires_grad)

True
True
False
True


# Binary Classification - Titanic: Machine Learning from Disaster

https://www.kaggle.com/c/titanic

- 유명한 자료인 타이타닉 데이터 셋으로 생존과 사망에 대한 분류 문제를 풀어보도록 하겠습니다.

## Prepare data

In [61]:
import os
from google.colab import drive


drive.mount('/content/drive')
os.chdir('/content/drive/MyDrive/Colab Notebooks/수업/20211223(deeplearning)') 

Mounted at /content/drive


In [72]:
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
import random
import pandas as pd
import matplotlib.pyplot as plt
from torch.utils.data import Dataset
from torch.utils.data import DataLoader
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split


random.seed(42)
torch.manual_seed(42)

In [73]:
train_data = pd.read_csv("./data/titanic/train.csv")
test_data = pd.read_csv("./data/titanic/test.csv")

In [74]:
train_data.head()

PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S
3            4         1       1  ...  53.1000  C123         S
4            5         0       3  ...   8.0500   NaN         S

[5 rows x 12 columns]

In [75]:
test_data.head()

PassengerId  Pclass  ... Cabin Embarked
0          892       3  ...   NaN        Q
1          893       3  ...   NaN        S
2          894       2  ...   NaN        Q
3          895       3  ...   NaN        S
4          896       3  ...   NaN        S

[5 rows x 11 columns]

## Preprocessing

### categorical variable processing

In [76]:
train_data['Sex'].head()

0      male
1    female
2    female
3    female
4      male
Name: Sex, dtype: object

In [77]:
# One-hot encoding
train_data['Sex'] = train_data['Sex'].map({'male': 1, 'female': 0})
test_data['Sex'] = test_data['Sex'].map({'male': 1, 'female': 0})

In [78]:
train_data['Sex'].head()

0    1
1    0
2    0
3    0
4    1
Name: Sex, dtype: int64

### Select feature

In [79]:
data_X = train_data[['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare']]
data_y = train_data['Survived']

In [80]:
len(data_X)

891

In [81]:
train_X, test_X, train_y, test_y = train_test_split(data_X, data_y, test_size=0.3, random_state=42)

In [82]:
len(train_X), len(data_X) * 0.7

(623, 623.6999999999999)

In [83]:
len(test_X), len(data_X) * 0.3

(268, 267.3)

### Check null

In [85]:
print('Number of null in train_X:', train_X.isnull().sum())
print("\n",'Number of null in test_X:', test_X.isnull().sum())
print("\n",'Number of nullin train y:', train_y.isnull().sum())
print("\n",'Number of nullin train y:', test_y.isnull().sum())

print("\n",np.mean(data_X["Age"]))

Number of null in train_X: Pclass      0
Sex         0
Age       124
SibSp       0
Parch       0
Fare        0
dtype: int64

 Number of null in test_X: Pclass     0
Sex        0
Age       53
SibSp      0
Parch      0
Fare       0
dtype: int64

 Number of nullin train y: 0

 Number of nullin train y: 0

 29.69911764705882


In [86]:
# interpolation null value of age and fare to mean
train_X.loc[:, 'Age'] = train_X.loc[:, 'Age'].replace(np.nan, 30)
test_X.loc[:, 'Age'] = test_X.loc[:, 'Age'].replace(np.nan, 30)

In [87]:
print('Number of null in train:', train_X.isnull().sum())
print('Number of null in test:', test_X.isnull().sum())

Number of null in train: Pclass    0
Sex       0
Age       0
SibSp     0
Parch     0
Fare      0
dtype: int64
Number of null in test: Pclass    0
Sex       0
Age       0
SibSp     0
Parch     0
Fare      0
dtype: int64


In [88]:
len(train_X), len(train_y), len(test_X), len(test_y)

(623, 623, 268, 268)

## Train model (Pytorch)

<h2>Step of learning</h2>

1. Define dataset & dataloader
2. Define model
3. Model Learning
4. Model evaluation

### 1. Define dataset & dataloader

In [95]:
class SimpleDataset(Dataset):
    
    def __init__(self, X_data, y_data):
        self.X_data = X_data
        self.y_data = y_data
    
    def __getitem__(self, index):
        return self.X_data[index], self.y_data[index]
    
    def __len__(self):
        return len(self.X_data)

In [96]:
# Standardization
scaler = StandardScaler()
train_data = SimpleDataset(torch.FloatTensor(scaler.fit_transform(train_X.to_numpy())), torch.LongTensor(train_y.to_numpy()))
test_data = SimpleDataset(torch.FloatTensor(scaler.transform(test_X.to_numpy())), torch.LongTensor(test_y.to_numpy()))

In [97]:
len(train_data), len(test_data)

(623, 268)

In [98]:
train_data.__getitem__(0)

(tensor([-1.6379,  0.7208, -1.9512, -0.4742,  1.9989,  0.9810]), tensor(1))

In [99]:
train_data[0]

(tensor([-1.6379,  0.7208, -1.9512, -0.4742,  1.9989,  0.9810]), tensor(1))

### 2. Define model

In [100]:
class BinaryClassification(nn.Module):

    def __init__(self, num_features, num_classes):
        super(BinaryClassification, self).__init__() # https://dojang.io/mod/page/view.php?id=2386

        self.Layer_1 = nn.Linear(num_features, 30)
        self.Layer_2 = nn.Linear(30, 15)
        self.Layer_3 = nn.Linear(15, 8)
        self.Layer_out = nn.Linear(8, num_classes)
        
        self.relu = nn.ReLU()
    
    def forward(self, inputs):
        x = self.Layer_1(inputs)
        x = self.relu(x)

        x = self.Layer_2(x)
        x = self.relu(x)

        x = self.Layer_3(x)
        x = self.relu(x)

        x = self.Layer_out(x)

        return x


### 3. Model Learning

In [108]:
EPOCHS = 3000
BATCH_SIZE = 64

train_loader = DataLoader(dataset=train_data, batch_size=BATCH_SIZE, shuffle=True)
test_loader = DataLoader(dataset=test_data, batch_size=1, shuffle=False)

model = BinaryClassification(num_features=6, num_classes=2)

criterion = nn.CrossEntropyLoss() # https://pytorch.org/docs/stable/nn.htm
optimizer = optim.Adam(model.parameters(), lr=0.001)

In [109]:
for X_batch, y_batch in train_loader:
    print(X_batch.size(), y_batch.size())
    break

torch.Size([64, 6]) torch.Size([64])


In [110]:
loss_list = []
acc_list = []
for epoch in range(EPOCHS):
    for i, (X_batch, y_batch) in enumerate(train_loader):
        # Forward
        y_output = model(X_batch)
        loss = criterion(y_output, y_batch)

        # Backward
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        # misc
        y_pred = torch.max(y_output, 1)[1]
        acc = accuracy_score(y_pred.data.cpu(), y_batch.data.cpu())
        loss_list.append(loss.item())
        acc_list.append(acc)

        if (epoch+1) % 100 == 0:
            print('Epoch [{}/{}] Step [{}/{}] Loss: [{:.4f}] Train ACC [{:.2f}%]'.format(epoch+1, EPOCHS, i+1, len(train_loader), loss.item(), acc*100))


Epoch [100/3000] Step [1/10] Loss: [0.3072] Train ACC [82.81%]
Epoch [100/3000] Step [2/10] Loss: [0.2683] Train ACC [90.62%]
Epoch [100/3000] Step [3/10] Loss: [0.3881] Train ACC [85.94%]
Epoch [100/3000] Step [4/10] Loss: [0.3492] Train ACC [82.81%]
Epoch [100/3000] Step [5/10] Loss: [0.4175] Train ACC [81.25%]
Epoch [100/3000] Step [6/10] Loss: [0.4066] Train ACC [82.81%]
Epoch [100/3000] Step [7/10] Loss: [0.3854] Train ACC [81.25%]
Epoch [100/3000] Step [8/10] Loss: [0.4332] Train ACC [84.38%]
Epoch [100/3000] Step [9/10] Loss: [0.3487] Train ACC [87.50%]
Epoch [100/3000] Step [10/10] Loss: [0.3695] Train ACC [87.23%]
Epoch [200/3000] Step [1/10] Loss: [0.2792] Train ACC [92.19%]
Epoch [200/3000] Step [2/10] Loss: [0.3951] Train ACC [85.94%]
Epoch [200/3000] Step [3/10] Loss: [0.3216] Train ACC [85.94%]
Epoch [200/3000] Step [4/10] Loss: [0.3537] Train ACC [85.94%]
Epoch [200/3000] Step [5/10] Loss: [0.3603] Train ACC [84.38%]
Epoch [200/3000] Step [6/10] Loss: [0.3573] Train ACC 

### 4. Model evaluation

In [112]:
test_y_pred = []
test_acc_list = []
with torch.no_grad():
    for X_batch, y_batch in test_loader:
        # Forward
        y_output = model(X_batch)

        # misc
        y_pred = torch.max(y_output, 1)[1]
        test_y_pred.append(y_pred)

        acc = accuracy_score(y_pred.data.cpu(), y_batch.data.cpu())
        test_acc_list.append(acc)
    test_acc = np.mean(test_acc_list)
print('Test ACC: [{:.2f}%]'.format(test_acc * 100))

Test ACC: [77.61%]
